from __future__ import annotations
from typing import Protocol, Iterable, Optional
from datetime import date
from .entities import BankAccount, Category, Operation


class BankAccountRepository(Protocol):
    def add(self, account: BankAccount) -> None: ...
    def update(self, account: BankAccount) -> None: ...
    def delete(self, account_id: str) -> None: ...
    def get(self, account_id: str) -> Optional[BankAccount]: ...
    def list_all(self) -> Iterable[BankAccount]: ...


class CategoryRepository(Protocol):
    def add(self, category: Category) -> None: ...
    def update(self, category: Category) -> None: ...
    def delete(self, category_id: str) -> None: ...
    def get(self, category_id: str) -> Optional[Category]: ...
    def list_all(self) -> Iterable[Category]: ...
    def list_by_type(self, type_: str) -> Iterable[Category]: ...


class OperationRepository(Protocol):
    def add(self, operation: Operation) -> None: ...
    def delete(self, operation_id: str) -> None: ...
    def get(self, operation_id: str) -> Optional[Operation]: ...
    def list_all(self) -> Iterable[Operation]: ...
    def list_by_account(self, account_id: str) -> Iterable[Operation]: ...

    def list_by_period(
        self,
        date_from: date,
        date_to: date) -> Iterable[Operation]: ...
